language: r
dist: bionic
latex: false # Only because I'm manually installing TinyTex!

# Cache (i.e. persist across builds) some stuff that's not needed to be re-built
cache:
  packages: yes
  directories:
    - $HOME/bin       # Where webshot installs phantomjs
    - $HOME/.fonts    # Where fonts are downloaded to & installed
    - $HOME/.TinyTex  # Aforementioned TinyTex dir
    - $TRAVIS_BUILD_DIR/_bookdown_files # Rendered images cache
    - $HOME/.local/share/renv # renv
    - $TRAVIS_BUILD_DIR/renv/library

addons:
  ssh_known_hosts: pearson.tadaa-data.de:54321

env:
  - BOOKDOWN_FORMAT="bookdown::gitbook"
  # - BOOKDOWN_FORMAT="bookdown::epub_book"
  - BOOKDOWN_FORMAT="bookdown::pdf_book"

apt_packages:
  - fonts-oflb-asana-math # Asana Math font that may be not needed
  - fonts-roboto # Good ol' Roboto font family!

before_install:
  - Rscript -e "renv::restore()"
  - |
    mkdir -p $HOME/.fonts

    # Only do this for pdf output
    if [[ "$BOOKDOWN_FORMAT" == "bookdown::pdf_book" ]]; then

      # 1. Install TinyTex manually
      if [ ! -d $HOME/.TinyTex/bin ]; then
        Rscript -e "tinytex::install_tinytex()"
      fi

      #if [ ! -x "$(command -v xelatex)" ]; then
      #  Rscript -e "tinytex::install_tinytex()"
      #fi

      # Install phantomjs to capture htmlwidget output
      [ -x "$HOME/bin/phantomjs" ] || Rscript -e "webshot::install_phantomjs()"

      # Copy fontconfig for possibly maybe xelatex font issue with spaces in font names
      cp $HOME/.TinyTeX/texmf-var/fonts/conf/texlive-fontconfig.conf ~/.fonts.conf
    fi

    # Update font cache for previously installed fonts (+ list fonts for debugging)
    fc-cache -fv
    fc-list

# Render the actual book, format depending on env var BOOKDOWN_FORMAT
script:
  - "Rscript -e \"bookdown::render_book('index.Rmd', '$BOOKDOWN_FORMAT')\""

# Manualy copy over a header image
# There is probably a "correct" way to have bookdown do this for us, but oh well.
after_success:
  - test $BOOKDOWN_FORMAT = "bookdown::gitbook" && cp images/tadaa_thin_t.png book/images/

# If something fails, show the latex log file.
after_failure:
  - "[ $BOOKDOWN_FORMAT = 'bookdown::pdf_book' ] && cat r-intro.log"

# Deploy to our server via rsync and ssh shenanigans
before_deploy:
  - openssl aes-256-cbc -K $encrypted_c75080516f68_key -iv $encrypted_c75080516f68_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet $TRAVIS_BUILD_DIR/book -e 'ssh -p 54321' travis@pearson.tadaa-data.de:/srv/r-intro.tadaa-data.de
  on:
    branch: master

notifications:
  email: false
